sonar.projectKey=SalePartido
sonar.projectName=Sale Partido
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

# Fuentes (solo backend por ahora)
sonar.sources=backend/src/main/java
sonar.tests=backend/src/test/java
sonar.test.inclusions=**/*Test.java,**/*Tests.java

# Exclusiones
sonar.exclusions=\
  **/target/**,\
  **/*Application.java

sonar.coverage.exclusions=\
  **/config/**,\
  **/dto/**,\
  **/entity/**,\
  **/exception/**,\
  **/mapper/**

# Backend - Java
sonar.java.binaries=backend/target/classes
sonar.java.test.binaries=backend/target/test-classes
sonar.java.libraries=backend/target/dependency
