apiVersion: apps/v1
kind: Deployment
metadata:
  name: salepartido-backend
  namespace: salepartido
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: salepartido-backend:latest 
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://salepartido-postgres:5432/salepartido_database"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: salepartido-config
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: salepartido-secret
              key: POSTGRES_PASSWORD
        - name: SPRING_DATA_REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: salepartido-config
              key: REDIS_HOST
        - name: SPRING_DATA_REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: salepartido-config
              key: REDIS_PORT
        - name: SPRING_JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: salepartido-secret
              key: SPRING_JWT_SECRET_KEY
        - name: SPRING_PORT
          valueFrom:
            configMapKeyRef:
              name: salepartido-config
              key: SPRING_PORT
        - name: SPRING_DATA_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: salepartido-secret
              key: REDIS_PASSWORD
        - name: SPRING_DATA_REDIS_DATABASE
          valueFrom:
            configMapKeyRef:
              name: salepartido-config
              key: REDIS_DATABASE
        - name: SPRING_CORS
          valueFrom:
            configMapKeyRef:
              name: salepartido-config
              key: SPRING_CORS
---
apiVersion: v1
kind: Service
metadata:
  name: salepartido-backend
  namespace: salepartido
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
