apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: salepartido-ingress
  namespace: salepartido
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: sale-partido.com # Change to your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: salepartido-frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: salepartido-backend
            port:
              number: 8080
