spring.application.name=api
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=jdbc:postgresql://salepartido-database:5432/${POSTGRES_DB_NAME}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.data.redis.host=${SPRING_REDIS_HOST}
spring.data.redis.port=6379

jwt.secretkey=${SPRING_JWT_SECRET_KEY}
cors.allowed-origin=http://localhost:8080